name: Master CI Build

on:
  push:
    branches:
#      - master
      - translation-experiment

jobs:
  build_en_docs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]

    name: Build and upload english docs
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U Sphinx==2.4.4
        pip install --upgrade recommonmark
        pip install sphinx_rtd_theme
    - name: Build documentation
      shell: bash
      run: |
        cd docs
        make html
    - name: Upload documentation
      uses: JulianGro/SFTP-Deploy-Action@v1.2
      with:
        username: 'gha'
        server: '94.130.177.235'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: 'docs/build/html/*'
        remote_path: '/var/www/html/gha/'
        args: '-o ConnectTimeout=5'

  update_translation_files:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]

    name: Update translation files
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U Sphinx==2.4.4
        pip install --upgrade recommonmark
        pip install sphinx_rtd_theme
    - name: Make gettext
      shell: bash
      run: |
        cd docs
        make gettext
    - name: Generate updated language files
      shell: bash
      run: |
        cd docs
        sphinx-intl update -l de
    - name: Commit updated language files
      shell: bash
      run: |
        git config --global user.name 'Github Actions'
        git commit -am "Automated translation file update"
        git push

  build_de_docs:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]

    name: Build and upload german docs
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U Sphinx==2.4.4
        pip install --upgrade recommonmark
        pip install sphinx_rtd_theme
    - name: Build documentation
      shell: bash
      run: |
        cd docs
        make BUILDDIR=build-de SPHINXOPTS="-Dlanguage=de" html
    - name: Upload documentation
      uses: JulianGro/SFTP-Deploy-Action@v1.2
      with:
        username: 'gha'
        server: '94.130.177.235'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: 'docs/build-de/html/*'
        remote_path: '/var/www/html/gha/de/'
        args: '-o ConnectTimeout=5'